# Generated by Django 5.2.6 on 2025-09-23 21:13

import uuid

import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("riders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rider",
            name="is_removed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="rider",
            name="id",
            field=model_utils.fields.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
