# Generated by Django 6.0a1 on 2025-09-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationcode",
            name="has_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
