# Generated by Django 5.2.7 on 2025-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="spot",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The bike spot/puesto number chosen for this reservation.",
                null=True,
            ),
        ),
    ]
