# Generated by Django 5.2.7 on 2026-08-21 00:13

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_reservation_spot"),
        ("schedules", "0003_alter_schedule_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaitlistEntry",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("OFFERED", "Offered"),
                            ("CONVERTED", "Converted"),
                            ("LEFT", "Left"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="WAITING",
                        max_length=20,
                    ),
                ),
                (
                    "offered_spot",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Spot offered to this member when a reservation is cancelled.",
                        null=True,
                    ),
                ),
                ("offered_at", models.DateTimeField(blank=True, null=True)),
                ("offer_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "converted_reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waitlist_conversions",
                        to="members.reservation",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="members.member",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waitlist_entries",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("is_removed", False), ("status__in", ("WAITING", "OFFERED"))
                        ),
                        fields=("member", "schedule"),
                        name="uniq_active_waitlist_member_schedule",
                    )
                ],
            },
        ),
    ]
