# Generated by Django 5.2.7 on 2026-09-03 20:58

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0005_promote_axel_diaz_coach"),
        ("members", "0005_reservation_credit_and_cancellation"),
        ("studios", "0004_studiosettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertDelivery",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_key", models.CharField(max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[("SCHEDULE", "Schedule"), ("SPOT", "Spot")], max_length=20
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_deliveries",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "event_key", "kind"),
                        name="uniq_alert_delivery_event_member_kind",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AlertPreference",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("quiet_hours_start", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("quiet_hours_end", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_preference",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quiet_hours_start__isnull", True),
                            models.Q(("quiet_hours_start__gte", 0), ("quiet_hours_start__lte", 23)),
                            _connector="OR",
                        ),
                        name="alert_preference_quiet_start_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("quiet_hours_end__isnull", True),
                            models.Q(("quiet_hours_end__gte", 0), ("quiet_hours_end__lte", 23)),
                            _connector="OR",
                        ),
                        name="alert_preference_quiet_end_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriteInstructor",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by_members",
                        to="instructors.instructor",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_instructors",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("member", "instructor"), name="uniq_favorite_instructor_per_member"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriteSpot",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("spot", models.PositiveIntegerField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_spots",
                        to="members.member",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_spots",
                        to="studios.room",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("spot__gt", 0)), name="favorite_spot_positive"
                    ),
                    models.UniqueConstraint(
                        fields=("member", "room", "spot"), name="uniq_favorite_spot_per_member"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FavoriteTimeSlot",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(help_text="Monday is 0 and Sunday is 6."),
                ),
                ("start_hour", models.PositiveSmallIntegerField()),
                ("end_hour", models.PositiveSmallIntegerField()),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_time_slots",
                        to="members.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("weekday__gte", 0), ("weekday__lte", 6)),
                        name="favorite_time_slot_weekday_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("start_hour__gte", 0), ("start_hour__lte", 23)),
                        name="favorite_time_slot_start_hour_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_hour__gte", 1), ("end_hour__lte", 24)),
                        name="favorite_time_slot_end_hour_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_hour__gt", models.F("start_hour"))),
                        name="favorite_time_slot_positive_duration",
                    ),
                    models.UniqueConstraint(
                        fields=("member", "weekday", "start_hour", "end_hour"),
                        name="uniq_favorite_time_slot_per_member",
                    ),
                ],
            },
        ),
    ]
