# Generated by Django 5.2.7 on 2026-09-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_reservation_attendance_metadata"),
        ("schedules", "0006_schedule_check_in_qr_version"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["schedule", "is_removed", "status"], name="reservation_sched_occ_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["member", "is_removed"], name="reservation_member_idx"),
        ),
    ]
