# Generated by Django 5.2.7 on 2026-09-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0007_reservation_attendance_metadata"),
        ("schedules", "0005_scheduleinstructorsubstitution"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the day-before class reminder email was sent for this reservation.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(
                fields=["schedule", "is_removed", "status"], name="reservation_sched_occ_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["member", "is_removed"], name="reservation_member_idx"),
        ),
    ]
