# Generated by Django 5.2.7 on 2026-09-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0008_cyc79_hot_path_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the day-before class reminder email was sent for this reservation.",
                null=True,
            ),
        ),
    ]
