# Generated by Django 5.2.7 on 2025-12-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
