services:
  web:
    build: .
    user: "1000:1000"
    command: >
      sh -c "
      python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      gunicorn adminstudio_django.wsgi:application --bind 0.0.0.0:80 --workers 3 --threads 2 --timeout 120
      "
    ports:
      - "80:80"
    environment:
      DJANGO_SETTINGS_MODULE: adminstudio_django.settings.prod
      DJANGO_DEBUG: "False"
      DJANGO_ENV: "prod"
    volumes:
      - sqlite_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  sqlite_data: