# Generated by Django 5.2.7 on 2025-11-30 14:14

import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("terms_and_conditions", "Términos y Condiciones"),
                            ("privacy_policy", "Política de Privacidad"),
                            ("waiver", "Renuncia de Responsabilidad"),
                            ("cookie_policy", "Política de Cookies"),
                            ("refund_policy", "Política de Reembolsos"),
                        ],
                        help_text="Tipo de documento legal",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(help_text="Título del documento", max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug único para el documento", max_length=255, unique=True
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Contenido del documento en formato Markdown"),
                ),
                (
                    "language",
                    models.CharField(
                        default="es", help_text="Código de idioma (es, en, etc.)", max_length=10
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Versión del documento (ej: 1.0, 1.1, 2.0)",
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(help_text="Fecha de vigencia del documento")),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Si está publicado, aparecerá en el endpoint público",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Orden de visualización (para múltiples documentos del mismo tipo)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Legal",
                "verbose_name_plural": "Documentos Legales",
                "ordering": ["document_type", "order", "-effective_date", "title"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "is_published", "language"],
                        name="legal_legal_documen_dbaf18_idx",
                    ),
                    models.Index(fields=["slug"], name="legal_legal_slug_ed5ad8_idx"),
                ],
                "unique_together": {("document_type", "language", "version")},
            },
        ),
    ]
