# Generated by Django 5.2.7 on 2025-11-27 12:36

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Nombre de la sección", max_length=100, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug único para la sección", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", help_text="Descripción opcional de la sección"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Orden de visualización"),
                ),
            ],
            options={
                "verbose_name": "Sección",
                "verbose_name_plural": "Secciones",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FAQItem",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("question", models.CharField(help_text="Pregunta", max_length=255)),
                ("answer", models.TextField(help_text="Respuesta en formato Markdown")),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Orden dentro de la sección"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Si está publicado, aparecerá en el endpoint público",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Sección a la que pertenece esta pregunta",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="faqs.section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregunta Frecuente",
                "verbose_name_plural": "Preguntas Frecuentes",
                "ordering": ["section__order", "order", "question"],
                "indexes": [
                    models.Index(
                        fields=["section", "is_published", "order"],
                        name="faqs_faqitem_section_a33177_idx",
                    )
                ],
            },
        ),
    ]
