# Generated by Django 5.2.7 on 2025-11-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faqs", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="faqitem",
            new_name="faqs_faqite_section_d29697_idx",
            old_name="faqs_faqitem_section_a33177_idx",
        ),
    ]
