# Generated by Django 5.2.7 on 2026-09-03 17:41

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocSection",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("member", "Miembros"),
                            ("admin", "Admin"),
                            ("coach", "Coach"),
                            ("platform", "Plataforma"),
                        ],
                        default="member",
                        help_text="Audiencia a la que está dirigida esta sección",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(help_text="Título de la sección", max_length=160)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Slug único de la sección", max_length=160, unique=True
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Orden de visualización"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Si está publicado, aparecerá en el índice público"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sección de documentación",
                "verbose_name_plural": "Secciones de documentación",
                "ordering": ["audience", "order", "title"],
                "indexes": [
                    models.Index(
                        fields=["audience", "is_published", "order"],
                        name="docs_docsec_audienc_5f7149_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DocPage",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(help_text="Título del artículo", max_length=255)),
                (
                    "slug",
                    models.SlugField(help_text="Slug único dentro de la sección", max_length=255),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Resumen corto para el índice",
                        max_length=400,
                    ),
                ),
                (
                    "body",
                    models.TextField(blank=True, default="", help_text="Cuerpo HTML del artículo"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, help_text="Orden dentro de la sección"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Si está publicado, aparecerá en el endpoint público",
                    ),
                ),
                (
                    "related_app_route",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Ruta de la app relacionada, por ejemplo #classes",
                        max_length=120,
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        help_text="Sección a la que pertenece este artículo",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="docs.docsection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artículo de documentación",
                "verbose_name_plural": "Artículos de documentación",
                "ordering": ["section__order", "order", "title"],
                "indexes": [
                    models.Index(
                        fields=["section", "is_published", "order"],
                        name="docs_docpag_section_257eaf_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("section", "slug"), name="docs_docpage_section_slug_uniq"
                    )
                ],
            },
        ),
    ]
