# Generated by Django 5.2.7 on 2026-09-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0007_add_remaining_coach_and_notification_guides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docsection",
            name="audience",
            field=models.CharField(
                choices=[
                    ("member", "Miembros"),
                    ("admin", "Staff"),
                    ("coach", "Coach"),
                    ("platform", "Plataforma"),
                ],
                default="member",
                help_text="Audiencia a la que está dirigida esta sección",
                max_length=20,
            ),
        ),
    ]
