# Generated by Django 5.2.7 on 2025-10-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="instructor",
            name="experience_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instructor",
            name="instagram_handle",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="instructor",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instructor",
            name="last_apple_music_playlist",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="instructor",
            name="last_spotify_playlist",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="instructor",
            name="last_youtube_music_playlist",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="instructor",
            name="location",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="instructor",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="instructors/profile_images/"),
        ),
        migrations.AddField(
            model_name="instructor",
            name="tagline",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="instructor",
            name="website_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
