# Generated by Django 5.2.7 on 2025-10-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_instructor_description_instructor_experience_years_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instructor",
            old_name="instagram_handle",
            new_name="instagram_username",
        ),
        migrations.RemoveField(
            model_name="instructor",
            name="experience_years",
        ),
        migrations.AddField(
            model_name="instructor",
            name="instructor_since",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instructor",
            name="tiktok_username",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
