# Generated by Django 5.2.7 on 2026-08-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0003_rename_instagram_handle_instructor_instagram_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="certifications",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="instructor",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="instructor",
            name="specialties",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
