# Generated by Django 5.2.7 on 2025-10-31 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studio",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studio",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
