# Generated by Django 5.2.7 on 2025-12-10 22:56

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.db import migrations, models, connection


def create_address_instances(apps, schema_editor):
    """
    Create Address instances for all unique addresses in Studio.
    Set Studio addresses to NULL temporarily to avoid constraint issues.
    We'll migrate the data in a separate migration after the schema change.
    """
    Studio = apps.get_model("studios", "Studio")
    Address = apps.get_model("studios", "Address")

    # Get all unique address strings and create Address instances
    studios = Studio.objects.exclude(address__isnull=True).exclude(address="")
    unique_addresses = set(studio.address for studio in studios if studio.address)

    # Create Address instances for all unique addresses
    for address_string in unique_addresses:
        Address.objects.get_or_create(
            address=address_string,
            defaults={
                "latitude": None,
                "longitude": None,
            },
        )

    # Set all Studio addresses to NULL temporarily to avoid constraint issues
    # We'll migrate the data in a separate migration after the schema change
    Studio.objects.exclude(address__isnull=True).exclude(address="").update(address=None)


def reverse_migrate_address_data(apps, schema_editor):
    """
    Reverse: set addresses to None (can't convert back to strings easily).
    """
    Studio = apps.get_model("studios", "Studio")
    Studio.objects.update(address=None)


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0002_studio_closing_time_studio_opening_time"),
    ]

    operations = [
        # Step 1: Create the Address model
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for this address.",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude for this address.",
                        max_digits=9,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        # Step 2: Make Studio.address nullable first
        migrations.AlterField(
            model_name="studio",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # Step 3: Create Address instances and set Studio addresses to NULL
        migrations.RunPython(create_address_instances, reverse_migrate_address_data),
        # Step 4: Change the field type from CharField to ForeignKey
        migrations.AlterField(
            model_name="studio",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="studios",
                to="studios.address",
            ),
        ),
    ]
