# Generated by Django 5.2

from django.db import migrations, models
import model_utils.fields
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("studios", "0003_address_alter_studio_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudioSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "free_cancellation_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Hours before class start when members can cancel for free.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Studio settings",
                "verbose_name_plural": "Studio settings",
            },
        ),
    ]
