# Generated by Django 5.2.6 on 2025-09-11 15:12
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("female", "Female"), ("male", "Male"), ("other", "Other")],
                default="other",
                max_length=10,
            ),
        ),
    ]
