# Generated by Django 5.2.7 on 2025-11-21 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_address_user_birthdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpiringToken",
            fields=[
                ("key", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, verbose_name="Created")),
                ("expires_at", models.DateTimeField(verbose_name="Expires At")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiring_token",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
                "db_table": "users_expiringtoken",
            },
        ),
    ]
