# Generated by Django 5.2.7 on 2025-11-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_expiringtoken"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExpiringToken",
        ),
    ]
