# Generated by Django 5.2.7 on 2025-12-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_delete_expiringtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="height_cm",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Height in centimeters.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="shoe_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Shoe size (e.g. 40.5).",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="weight_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight in kilograms.",
                max_digits=5,
                null=True,
            ),
        ),
    ]
