# Generated by Django 5.2.7 on 2025-12-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_height_cm_user_shoe_size_user_weight_kg"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cycling_shoe_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Cycling shoe size (e.g. 44.0).",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="extended_handlebar",
            field=models.BooleanField(
                default=False, help_text="Whether the handlebar is extended."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="handlebar_distance",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Handlebar distance in centimeters.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seat_distance",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Seat distance in centimeters.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="seat_height",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Seat height in centimeters.", null=True
            ),
        ),
    ]
