# Generated by Django 5.2.7 on 2025-12-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_cycling_shoe_size_user_extended_handlebar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="extended_handlebar",
        ),
    ]
