# Generated by Django 5.2.7 on 2026-08-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_passwordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="waitlist_auto_confirm",
            field=models.BooleanField(
                default=False,
                help_text="Automatically reserve a spot when one opens from the waitlist.",
            ),
        ),
    ]
