RESERVATION_STATUS_RESERVED = "RESERVED"
RESERVATION_STATUS_CANCELLED = "CANCELLED"
RESERVATION_STATUS_ATTENDED = "ATTENDED"
RESERVATION_STATUS_MISSED = "MISSED"

CANCELLATION_SOURCE_MEMBER = "member"
CANCELLATION_SOURCE_STUDIO = "studio"
CANCELLATION_SOURCE_SCHEDULE = "schedule"

STUDIO_CANCELLATION_SOURCES = (
    CANCELLATION_SOURCE_STUDIO,
    CANCELLATION_SOURCE_SCHEDULE,
)

WAITLIST_STATUS_WAITING = "WAITING"
WAITLIST_STATUS_OFFERED = "OFFERED"
WAITLIST_STATUS_CONVERTED = "CONVERTED"
WAITLIST_STATUS_LEFT = "LEFT"
WAITLIST_STATUS_EXPIRED = "EXPIRED"

WAITLIST_ACTIVE_STATUSES = (
    WAITLIST_STATUS_WAITING,
    WAITLIST_STATUS_OFFERED,
)

WAITLIST_OFFER_MINUTES = 15

# Response messages
RESERVATION_CANCELLED_SUCCESS_MESSAGE = "Reservation cancelled successfully."
WAITLIST_LEFT_SUCCESS_MESSAGE = "Saliste de la lista de espera."
WAITLIST_CONFIRMED_SUCCESS_MESSAGE = "Tu spot fue confirmado."
