RESERVATION_STATUS_RESERVED = "RESERVED"
RESERVATION_STATUS_CANCELLED = "CANCELLED"
RESERVATION_STATUS_ATTENDED = "ATTENDED"
RESERVATION_STATUS_MISSED = "MISSED"

# Response messages
RESERVATION_CANCELLED_SUCCESS_MESSAGE = "Reservation cancelled successfully."
