# Generated by Django 5.2.7 on 2025-10-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="benefits",
            field=models.ManyToManyField(blank=True, related_name="plans", to="plans.benefit"),
        ),
    ]
