# Generated by Django 5.2.7 on 2025-10-23 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_alter_plan_benefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="is_highlighted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_popular",
            field=models.BooleanField(default=False),
        ),
    ]
