# Generated by Django 5.2.7 on 2025-10-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0003_plan_is_highlighted_plan_is_popular"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="classes_included",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
