# Generated by Django 5.2.7 on 2025-11-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0004_alter_plan_classes_included"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="guest_passes_included",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
