# Generated by Django 5.2.7 on 2025-11-17 16:11

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plans", "0005_plan_guest_passes_included"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanPurchase",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "price_paid",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Price Paid"),
                ),
                ("is_activated", models.BooleanField(default=False, verbose_name="Activated")),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="plans.plan",
                        verbose_name="Purchased Plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plan_purchases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Purchase",
                "verbose_name_plural": "Plan Purchases",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("class_credits", models.IntegerField(default=0, verbose_name="Class Credits")),
                (
                    "guest_pass_credits",
                    models.IntegerField(default=0, verbose_name="Guest Pass Credits"),
                ),
                (
                    "active_membership_end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Active Membership End Date"
                    ),
                ),
                (
                    "retail_discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Retail Discount (%)",
                    ),
                ),
                (
                    "is_priority_booker",
                    models.BooleanField(default=False, verbose_name="Priority Booking Active"),
                ),
                (
                    "can_freeze_membership",
                    models.BooleanField(default=False, verbose_name="Freeze Membership Option"),
                ),
                (
                    "is_founders_exclusive",
                    models.BooleanField(default=False, verbose_name="Founders Pass Benefit"),
                ),
                (
                    "is_unlimited_membership_active",
                    models.BooleanField(default=False, verbose_name="Unlimited Membership"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Owner User",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
