# Generated by Django 5.2.7 on 2025-11-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planpurchase",
            name="is_activated",
        ),
        migrations.AddField(
            model_name="planpurchase",
            name="activated_since",
            field=models.DateField(blank=True, null=True, verbose_name="Activated Since"),
        ),
        migrations.AddField(
            model_name="planpurchase",
            name="end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="end"),
        ),
        migrations.AddField(
            model_name="planpurchase",
            name="start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="start"),
        ),
    ]
