# Generated by Django 5.2.7 on 2026-08-22 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0006_promocode_and_purchase_fields"),
        ("wallets", "0002_remove_planpurchase_is_activated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="planpurchase",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Discount Amount"
            ),
        ),
        migrations.AddField(
            model_name="planpurchase",
            name="payment_method",
            field=models.CharField(blank=True, max_length=32, verbose_name="Payment method"),
        ),
        migrations.AddField(
            model_name="planpurchase",
            name="promo_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="plans.promocode",
                verbose_name="Promo code",
            ),
        ),
        migrations.AddField(
            model_name="planpurchase",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Quantity"),
        ),
    ]
