# Generated by Django 5.2.7 on 2026-09-04 01:42

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_favorite_alerts"),
        ("schedules", "0005_scheduleinstructorsubstitution"),
        ("wallets", "0005_giftcard_delivery_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GuestPassInvitation",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("guest_name", models.CharField(max_length=150)),
                ("guest_email", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, max_length=1000)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("issued", "Issued"),
                            ("claimed", "Claimed"),
                            ("booked", "Booked"),
                            ("attended", "Attended"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="issued",
                        max_length=16,
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("waiver_accepted_at", models.DateTimeField(blank=True, null=True)),
                ("waiver_version", models.CharField(blank=True, max_length=20)),
                ("credit_consumed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RenameIndex(
            model_name="giftcard",
            new_name="wallets_gif_status_86afcb_idx",
            old_name="wallets_gif_status_9ed4c9_idx",
        ),
        migrations.RenameIndex(
            model_name="giftcard",
            new_name="wallets_gif_recipie_da4da6_idx",
            old_name="wallets_gif_recipie_c2614c_idx",
        ),
        migrations.AddField(
            model_name="guestpassinvitation",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claimed_guest_passes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guestpassinvitation",
            name="issuer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="guest_pass_invitations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="guestpassinvitation",
            name="reservation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_pass_invitation",
                to="members.reservation",
            ),
        ),
        migrations.AddField(
            model_name="guestpassinvitation",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="guest_pass_invitations",
                to="schedules.schedule",
            ),
        ),
        migrations.AddIndex(
            model_name="guestpassinvitation",
            index=models.Index(
                fields=["status", "expires_at"], name="wallets_gue_status_8d6682_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="guestpassinvitation",
            index=models.Index(fields=["issuer", "status"], name="wallets_gue_issuer__ce5dab_idx"),
        ),
        migrations.AddIndex(
            model_name="guestpassinvitation",
            index=models.Index(
                fields=["guest_email", "status"], name="wallets_gue_guest_e_66f34e_idx"
            ),
        ),
    ]
