# Generated by Django 5.2.7 on 2026-09-24 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0008_plan_is_first_timer"),
        ("wallets", "0006_guestpassinvitation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="planpurchase",
            index=models.Index(fields=["created"], name="planpurchase_created_idx"),
        ),
        migrations.AddIndex(
            model_name="planpurchase",
            index=models.Index(fields=["user", "created"], name="planpurchase_user_created_idx"),
        ),
    ]
