PLAN_TYPE_MEMBERSHIP = "MEMBERSHIP"
PLAN_TYPE_PACKAGE = "PACKAGE"
PLAN_TYPE_GIFT_CARD = "GIFT_CARD"
PLAN_TYPE_GIFT_PACK = "GIFT_PACK"

DISCOUNT_TYPE_PERCENT = "PERCENT"
DISCOUNT_TYPE_FIXED = "FIXED"

PAYMENT_METHOD_MERCADOPAGO = "mercadopago"
PAYMENT_METHOD_WEBPAY = "webpay"
