PLAN_TYPE_MEMBERSHIP = "MEMBERSHIP"
PLAN_TYPE_PACKAGE = "PACKAGE"

DISCOUNT_TYPE_PERCENT = "PERCENT"
DISCOUNT_TYPE_FIXED = "FIXED"

PAYMENT_METHOD_MERCADOPAGO = "mercadopago"
PAYMENT_METHOD_WEBPAY = "webpay"
