# Generated by Django 5.2.7 on 2025-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="schedule",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
