# Generated by Django 5.2.7 on 2025-10-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_schedule_description_schedule_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
