# Generated by Django 5.2.7 on 2026-09-24 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0005_promote_axel_diaz_coach"),
        ("schedules", "0006_schedule_check_in_qr_version"),
        ("studios", "0005_deactivate_demo_studios"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="schedule",
            index=models.Index(fields=["start_time"], name="schedule_start_time_idx"),
        ),
    ]
