name: Deploy to EC2 via SSH

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload project to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "."
          target: ${{ secrets.EC2_PATH }}
          rm: true
          overwrite: true
          strip_components: 0
          exclude: |
            .git*
            node_modules
            __pycache__

      - name: Build & Up via SSH (Docker Compose)
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            cd ${{ secrets.EC2_PATH }}
            docker compose version
            docker compose down || true
            docker compose up -d --build
            docker system prune -f