name: Ruff

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install dependencies (including Ruff)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show Ruff version
        run: ruff --version

      - name: Run ruff check
        run: ruff check .
